# Generated by Django 6.0.5 on 2026-05-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_customtest_customquestion_customtestresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_author',
            field=models.BooleanField(default=False, verbose_name='Автор (может создавать тесты)'),
        ),
    ]
