# Generated by Django 6.0.5 on 2026-05-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_profile_is_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_official',
            field=models.BooleanField(default=True, verbose_name='Официальный курс'),
        ),
    ]
