# Generated by Django 6.0.5 on 2026-05-27 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_course_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='main.customtest', verbose_name='Тест к уроку'),
        ),
    ]
