# Generated by Django 6.0.5 on 2026-05-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_lesson_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='additional_tests',
            field=models.ManyToManyField(blank=True, related_name='attached_courses', to='main.customtest', verbose_name='Дополнительные тесты'),
        ),
    ]
