# Generated by Django 5.2.14 on 2026-05-28 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_coursereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='communities', to='main.course', verbose_name='Связанные курсы'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_selected_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.course', verbose_name='Последний выбранный курс'),
        ),
    ]
