# Generated by Django 5.2.14 on 2026-05-28 18:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_community_courses_profile_last_selected_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='cover_image',
            field=models.URLField(blank=True, verbose_name='Ссылка на обложку'),
        ),
        migrations.AddField(
            model_name='community',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='community',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Закрытое сообщество'),
        ),
        migrations.AddField(
            model_name='community',
            name='join_password',
            field=models.CharField(blank=True, help_text='Для закрытых сообществ', max_length=100, verbose_name='Пароль для входа'),
        ),
        migrations.AddField(
            model_name='community',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_communities', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='community',
            name='rules',
            field=models.TextField(blank=True, verbose_name='Правила сообщества'),
        ),
        migrations.AddField(
            model_name='community',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL-идентификатор'),
        ),
        migrations.AddField(
            model_name='community',
            name='tags',
            field=models.CharField(blank=True, max_length=200, verbose_name='Теги (через запятую)'),
        ),
        migrations.CreateModel(
            name='CommunityExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('vkontakte', 'ВКонтакте (группа/паблик)'), ('vkontakte_video', 'ВКонтакте видео'), ('rutube', 'RUTUBE (канал)'), ('website', 'Веб-сайт'), ('other', 'Другое')], max_length=20, verbose_name='Тип ресурса')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Название')),
                ('icon_class', models.CharField(blank=True, max_length=50, verbose_name='Иконка (Font Awesome)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='main.community')),
            ],
            options={
                'verbose_name': 'Внешняя ссылка',
                'verbose_name_plural': 'Внешние ссылки',
                'ordering': ['community', 'order', 'link_type'],
            },
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст поста')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Закреплён')),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main.community')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_comments', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.communitypost')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Участник'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_banned', models.BooleanField(default=False)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='main.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('community', 'user')},
            },
        ),
    ]
