# Generated by Django 5.2.14 on 2026-05-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_community_has_chat_communitychatroom_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Одобрено модератором'),
        ),
    ]
