# Generated by Django 5.2.14 on 2026-05-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_community_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='Одобрено модератором'),
        ),
    ]
